### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by ackr-8** [ArshSB/DarkPDF#1]
I request you to add instructions to allow access to file URLs as without that local pdfs are not being darkened.
I really appreciate your effort for making this addon.

**Comment by ArshSB** [comment]
I'll add that, thanks for the suggestion! 

I had the instructions originally in extension description on Chrome Web Store but I realize now having it display in the extension itself is much more productive. I'm glad you found DarkPDF useful, cheers!
