### ISSUE TITLE
和"EdgeTranslate"配合使用,会失效

### ISSUE THREAD

**Issue by canbus** [ArshSB/DarkPDF#4]

**Comment by canbus** [comment]
https://github.com/EdgeTranslate/EdgeTranslate

**Comment by ArshSB** [comment]
Hi Canbus,

I am not sure what this issue is about. Please leave another comment with more details. If not, I'll be closing this issue soon. 

Thanks!

**Comment by canbus** [comment]
thanks,I leave another comment
