### ISSUE TITLE
Is it expected to work on MacOS?

### ISSUE THREAD

**Issue by siara-cc** [ArshSB/DarkPDF#6]
Hi, I could not get it to work on MacOS.  When I click on the DarkPDF icon, only the instructions appear and even Ctrl-Shift-9 or Cmd-Shift-9 does not seem to work on PDF documents opened within Chrome.

**Comment by ArshSB** [comment]
Hi there, 

Thanks for opening the issue. I checked with a friend's MacBook running macOS Monterey and the extension was working fine for him (worked on both local and online PDF files along with the keyboard shortcut).

I'm not sure what might be the problem in your case. Can you tell me what macOS version you are using?

**Comment by siara-cc** [comment]
Hi, thanks for the quick reply.  It worked after I enabled file URLs.  So it was just my misunderstanding.

However, I could not get it to darken the PDF itself, like the software Negative I use.  Please see the attached video.  Is it possible to do the same with DarkPDF?

https://user-images.githubusercontent.com/12986780/200814448-bd924123-cc40-4d6e-b783-e499a5911a01.mp4

In any case, thanks for making this extension. Great work!!

**Comment by ArshSB** [comment]
I've noticed a similar problem when using DarkPDF with other extensions/programs that interact with the PDF such as [DarkReader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en). The solution, of course, is to use only one of them at a time. 

Perhaps something else is also trying to do same thing as DarkPDF in Chrome? Does it do the same thing for online PDF files?

**Comment by siara-cc** [comment]
I don't have other similar extensions installed, but I found that the Auto Dark Mode setting I am using in chrome://flags is causing trouble:

![image](https://user-images.githubusercontent.com/12986780/201034659-81e837ef-7200-49e6-b74b-aa6ea460bc8e.png)

I am using this setting to see all web pages in dark mode as I was uncomfortable to install an extension for this purpose.

When this setting is disabled, DarkPDF works as intended.  Is there a way of making DarkPDF invert PDFs even if this is enabled?

**Comment by ArshSB** [comment]
Very interesting, I didn't know Chrome had that built-in feature!

Unfortunately, as far as I know, I don't have a way to fix this. DarkPDF injects some simple CSS on to the page to enable dark mode, and I believe other programs do something similar to achieve the same purpose, so when they both inject some CSS, they might interfere with each other. A possible solution would be identifying and fixing that interference in the HTML code, but that's beyond the scope of this extension 😞 

I did a quick test and it seems DarkReader extension works well in your case (has dark mode for PDFs while the `auto dark mode for web content` setting is enabled).

I appreciate your feedback on this, take care!

**Comment by siara-cc** [comment]
Thanks for the info on DarkReader!!  It works for both websites and PDFs as you said, even without the "Auto dark mode" setting.
