### ISSUE TITLE
Keeps glitching, little unstable 

### ISSUE THREAD

**Issue by Bhanu-tarun** [ArshSB/DarkPDF#8]
it turns the dark mode on and off randomly, very quickly too, u switch to another tab and when u come back less than 30 seconds later its back the way it was before, white.

**Comment by Bhanu-tarun** [comment]
I think it will be fixed when the, "reapplying the darkmode". Everytime the user comes back. Instead of this can it be made to apply once and just make it stay there?

**Comment by Bhanu-tarun** [comment]
It is supposed to show a tick mark everytime it activates dark mode, it does show that but it is not actually triggered for some reason.

**Comment by ArshSB** [comment]
Hi Bhanu,

Thank you for your feedback. This issue has already been discussed [here](https://github.com/ArshSB/DarkPDF/issues/7). I have this fix on my to-do list but feel free to give it a try yourself if you wish!
